In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url = "https://raw.githubusercontent.com/premlatamd/week03/refs/heads/main/hotel_bookings.csv"
df = pd.read_csv(url)
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

#R1

In [3]:
df.duplicated().sum()

np.int64(31994)

In [4]:
df.drop_duplicates(inplace=True)
df.duplicated().sum(),df.shape

(np.int64(0), (87396, 32))

In [5]:
pd.crosstab(
    df['is_repeated_guest'],
    df['is_canceled'],
    normalize='index'
)*100

is_canceled                0          1
is_repeated_guest
0                  71.703123  28.296877
1                  92.357247   7.642753

#R2

##*1. The data*

In [6]:
#grouping variables and one numeric variable
for col in df.columns:
  print(col,df[col].unique())

hotel ['Resort Hotel' 'City Hotel']
is_canceled [0 1]
lead_time [342 737   7  13  14   0   9  85  75  23  35  68  18  37  12  72 127  78
  48  60  77  99 118  95  96  69  45  40  15  36  43  70  16 107  47 113
  90  50  93  76   3   1  10   5  17  51  71  63  62 101   2  81 368 364
 324  79  21 109 102   4  98  92  26  73 115  86  52  29  30  33  32   8
 100  44  80  97  64  39  34  27  82  94 110 111  84  66 104  28 258 112
  65  67  55  88  54 292  83 105 280 394  24 103 366 249  22  91  11 108
 106  31  87  41 304 117  59  53  58 116  42 321  38  56  49 317   6  57
  19  25 315 123  46  89  61 312 299 130  74 298 119  20 286 136 129 124
 327 131 460 140 114 139 122 137 126 120 128 135 150 143 151 132 125 157
 147 138 156 164 346 159 160 161 333 381 149 154 297 163 314 155 323 340
 356 142 328 144 336 248 302 175 344 382 146 170 166 338 167 310 148 165
 172 171 145 121 178 305 173 152 354 347 158 185 349 183 352 177 200 192
 361 207 174 330 134 350 334 283 153 197 133 241 193 235 194 261 260 216
 169 209 238 215 141 189 187 223 284 214 202 211 168 230 203 188 232 709
 219 162 196 190 259 228 176 250 201 186 199 180 206 205 224 222 182 210
 275 212 229 218 208 191 181 179 246 255 226 288 253 252 262 236 256 234
 254 468 213 237 198 195 239 263 265 274 217 220 307 221 233 257 227 276
 225 264 311 277 204 290 266 270 294 319 282 251 322 291 269 240 271 184
 231 268 247 273 300 301 267 244 306 293 309 272 242 295 285 243 308 398
 303 245 424 279 331 281 339 434 357 325 329 278 332 343 345 360 348 367
 353 373 374 406 400 326 379 399 316 341 320 385 355 363 358 296 422 390
 335 370 376 375 397 289 542 403 383 384 359 393 337 362 365 435 386 378
 313 351 287 471 462 411 450 318 372 371 454 532 445 389 388 407 443 437
 451 391 405 412 419 420 426 433 440 429 418 447 461 605 457 475 464 482
 626 489 496 503 510 517 524 531 538 545 552 559 566 573 580 587 594 601
 608 615 622 629 396 410 395 423 408 409 448 465 387 414 476 479 467 490
 493 478 504 507 458 518 521 377 444 380 463]
arrival_date_year [2015 2016 2017]
arrival_date_month ['July' 'August' 'September' 'October' 'November' 'December' 'January'
 'February' 'March' 'April' 'May' 'June']
arrival_date_week_number [27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21
 22 23 24 25 26]
arrival_date_day_of_month [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]
stays_in_weekend_nights [ 0  1  2  4  3  6 13  8  5  7 12  9 16 18 19 10 14]
stays_in_week_nights [ 0  1  2  3  4  5 10 11  8  6  7 15  9 12 33 20 14 16 21 13 30 19 24 40
 22 42 50 25 17 32 26 18 34 35 41]
adults [ 2  1  3  4 40 26 50 27 55  0 20  6  5 10]
children [ 0.  1.  2. 10.  3. nan]
babies [ 0  1  2 10  9]
meal ['BB' 'FB' 'HB' 'SC' 'Undefined']
country ['PRT' 'GBR' 'USA' 'ESP' 'IRL' 'FRA' nan 'ROU' 'NOR' 'OMN' 'ARG' 'POL'
 'DEU' 'BEL' 'CHE' 'CN' 'GRC' 'ITA' 'NLD' 'DNK' 'RUS' 'SWE' 'AUS' 'EST'
 'CZE' 'BRA' 'FIN' 'MOZ' 'BWA' 'LUX' 'SVN' 'ALB' 'IND' 'CHN' 'MEX' 'MAR'
 'UKR' 'SMR' 'LVA' 'PRI' 'SRB' 'CHL' 'AUT' 'BLR' 'LTU' 'TUR' 'ZAF' 'AGO'
 'ISR' 'CYM' 'ZMB' 'CPV' 'ZWE' 'DZA' 'KOR' 'CRI' 'HUN' 'ARE' 'TUN' 'JAM'
 'HRV' 'HKG' 'IRN' 'GEO' 'AND' 'GIB' 'URY' 'JEY' 'CAF' 'CYP' 'COL' 'GGY'
 'KWT' 'NGA' 'MDV' 'VEN' 'SVK' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'SEN'
 'SYC' 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MKD' 'MYS' 'ARM' 'JPN' 'LKA' 'CUB'
 'CMR' 'BIH' 'MUS' 'COM' 'SUR' 'UGA' 'BGR' 'CIV' 'JOR' 'SYR' 'SGP' 'BDI'
 'SAU' 'VNM' 'PLW' 'QAT' 'EGY' 'PER' 'MLT' 'MWI' 'ECU' 'MDG' 'ISL' 'UZB'
 'NPL' 'BHS' 'MAC' 'TGO' 'TWN' 'DJI' 'STP' 'KNA' 'ETH' 'IRQ' 'HND' 'RWA'
 'KHM' 'MCO' 'BGD' 'IMN' 'TJK' 'NIC' 'BEN' 'VGB' 'TZA' 'GAB' 'GHA' 'TMP'
 'GLP' 'KEN' 'LIE' 'GNB' 'MNE' 'UMI' 'MYT' 'FRO' 'MMR' 'PAN' 'BFA' 'LBY'
 'MLI' 'NAM' 'BOL' 'PRY' 'BRB' 'ABW' 'AIA' 'SLV' 'DMA' 'PYF' 'GUY' 'LCA'
 'ATA' 'GTM' 'ASM' 'MRT' 'NCL' 'KIR' 'SDN' 'ATF' 'SLE' 'LAO']
market_segment ['Direct' 'Corporate' 'Online TA' 'Offline TA/TO' 'Complementary' 'Groups'
 'Undefined' 'Aviation']
distribution_channel ['Direct' 'Corporate' 'TA/TO' 'Undefined' 'GDS']
is_repeated_guest [0 1]
previous_cancellations [ 0  1  2  3 26 25 14  4 24 19  5 21  6 13 11]
previous_bookings_not_canceled [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 20 21 22 23 24
 25 27 28 29 30 19 26 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72]
reserved_room_type ['C' 'A' 'D' 'E' 'G' 'F' 'H' 'L' 'P' 'B']
assigned_room_type ['C' 'A' 'D' 'E' 'G' 'F' 'I' 'B' 'H' 'P' 'L' 'K']
booking_changes [ 3  4  0  1  2  5 17  6  8  7 10 16  9 13 12 20 14 15 11 21 18]
deposit_type ['No Deposit' 'Refundable' 'Non Refund']
agent [ nan 304. 240. 303.  15. 241.   8. 250. 115.   5. 175. 134. 156. 243.
 242.   3. 105.  40. 147. 306. 184.  96.   2. 127.  95. 146.   9. 177.
   6. 143. 244. 149. 167. 300. 171. 305.  67. 196. 152. 142. 261. 104.
  36.  26.  29. 258. 110.  71. 181.  88. 251. 275.  69. 248. 208. 256.
 314. 126. 281. 273. 253. 185. 330. 334. 328. 326. 321. 324. 313.  38.
 155.  68. 335. 308. 332.  94. 348. 310. 339. 375.  66. 327. 387. 298.
  91. 245. 385. 257. 393. 168. 405. 249. 315.  75. 128. 307.  11. 436.
   1. 201. 183. 223. 368. 336. 291. 464. 411. 481.  10. 154. 468. 410.
 390. 440. 495. 492. 493. 434.  57. 531. 420. 483. 526. 472. 429.  16.
 446.  34.  78. 139. 252. 270.  47. 114. 301. 193. 182. 135. 350. 195.
 352. 355. 159. 363. 384. 360. 331. 367.  64. 406. 163. 414. 333. 427.
 431. 430. 426. 438. 433. 418. 441. 282. 432.  72. 450. 180. 454. 455.
  59. 451. 254. 358. 469. 165. 467. 510. 337. 476. 502. 527. 479. 508.
 535. 302. 497. 187.  13.   7.  27.  14.  22.  17.  28.  42.  20.  19.
  45.  37.  61.  39.  21.  24.  41.  50.  30.  54.  52.  12.  44.  31.
  83.  32.  63.  60.  55.  56.  89.  87. 118.  86.  85. 210. 214. 129.
 179. 138. 174. 170. 153.  93. 151. 119.  35. 173.  58.  53. 133.  79.
 235. 192. 191. 236. 162. 215. 157. 287. 132. 234.  98.  77. 103. 107.
 262. 220. 121. 205. 378.  23. 296. 290. 229.  33. 286. 276. 425. 484.
 323. 403. 219. 394. 509. 111. 423.   4.  70.  82.  81.  74.  92.  99.
  90. 112. 117. 106. 148. 158. 144. 211. 213. 216. 232. 150. 267. 227.
 247. 278. 280. 285. 289. 269. 295. 265. 288. 122. 294. 325. 341. 344.
 346. 359. 283. 364. 370. 371.  25. 141. 391. 397. 416. 404. 299. 197.
  73. 354. 444. 408. 461. 388. 453. 459. 474. 475. 480. 449.]
company [ nan 110. 113. 270. 178. 240. 154. 144. 307. 268.  59. 204. 312. 318.
  94. 174. 274. 195. 223. 317. 281. 118.  53. 286.  12.  47. 324. 342.
 373. 371. 383.  86.  82. 218.  88.  31. 397. 392. 405. 331. 367.  20.
  83. 416.  51. 395. 102.  34.  84. 360. 394. 457. 382. 461. 478. 386.
 112. 486. 421.   9. 308. 135. 224. 504. 269. 356. 498. 390. 513. 203.
 263. 477. 521. 169. 515. 445. 337. 251. 428. 292. 388. 130. 250. 355.
 254. 543. 531. 528.  62. 120.  42.  81. 116. 530. 103.  39.  16.  92.
  61. 501. 165. 291. 290.  43. 325. 192. 108. 200. 465. 287. 297. 490.
 482. 207. 282. 437. 225. 329. 272.  28.  77. 338.  72. 246. 319. 146.
 159. 380. 323. 511. 407. 278.  80. 403. 399.  14. 137. 343. 346. 347.
 349. 289. 351. 353.  54.  99. 358. 361. 362. 366. 372. 365. 277. 109.
 377. 379.  22. 378. 330. 364. 401. 232. 255. 384. 167. 212. 514. 391.
 400. 376. 402. 396. 302. 398.   6. 370. 369. 409. 168. 104. 408. 413.
 148.  10. 333. 419. 415. 424. 425. 423. 422. 435. 439. 442. 448. 443.
 454. 444.  52. 459. 458. 456. 460. 447. 470. 466. 484. 184. 485.  32.
 487. 491. 494. 193. 516. 496. 499.  29.  78. 520. 507. 506. 512. 126.
  64. 242. 518. 523. 539. 534. 436. 525. 541.  40. 455. 410.  45.  38.
  49.  48.  67.  68.  65.  91.  37.   8. 179. 209. 219. 221. 227. 153.
 186. 253. 202. 216. 275. 233. 280. 309. 321.  93. 316.  85. 107. 350.
 279. 334. 348. 150.  73. 385. 418. 197. 450. 452. 115.  46.  76.  96.
 100. 105. 101. 122.  11. 139. 142. 127. 143. 140. 149. 163. 160. 180.
 238. 183. 222. 185. 217. 215. 213. 237. 230. 234.  35. 245. 158. 258.
 259. 260. 411. 257. 271.  18. 106. 210. 273.  71. 284. 301. 305. 293.
 264. 311. 304. 313. 288. 320. 314. 332. 341. 352. 243. 368. 393. 132.
 220. 412. 420. 426. 417. 429. 433. 446. 357. 479. 483. 489. 229. 481.
 497. 451. 492.]
days_in_waiting_list [  0  50  47  65 122  75 101 150 125  14  60  34 100  22 121  61  39   5
   1   8 107  43  52   2  11 142 116  13  44  97  83   4 113  18  20 185
  93 109   6  37 105 154  64  99  38  48  33  77  21  80  59  40  58  89
  53  49  69  87  91  57 111  79  98  85  63  15   3  41 224  31  56 187
 176  71  55  96 236 259 207 215 160 120  30  32  27  62  24 108 147 379
  70  35 178 330 223 174 162 391  68 193  10  76  16  28   9 165  17  25
  46   7  84 175 183  23 117  12  54  26  73  45  19  42  72  81  92  74
 167  36]
customer_type ['Transient' 'Contract' 'Transient-Party' 'Group']
adr [  0.    75.    98.   ... 266.75 209.25 157.71]
required_car_parking_spaces [0 1 2 8 3]
total_of_special_requests [0 1 3 2 4 5]
reservation_status ['Check-Out' 'Canceled' 'No-Show']
reservation_status_date ['2015-07-01' '2015-07-02' '2015-07-03' '2015-05-06' '2015-04-22'
 '2015-06-23' '2015-07-05' '2015-07-06' '2015-07-07' '2015-07-08'
 '2015-05-11' '2015-07-15' '2015-07-16' '2015-05-29' '2015-05-19'
 '2015-06-19' '2015-05-23' '2015-05-18' '2015-07-09' '2015-06-02'
 '2015-07-13' '2015-07-04' '2015-06-29' '2015-06-16' '2015-06-18'
 '2015-06-12' '2015-06-09' '2015-05-26' '2015-07-11' '2015-07-12'
 '2015-07-17' '2015-04-15' '2015-05-13' '2015-07-10' '2015-05-20'
 '2015-05-12' '2015-07-14' '2015-06-17' '2015-05-01' '2015-03-30'
 '2015-07-19' '2015-06-03' '2015-06-26' '2015-05-14' '2015-07-20'
 '2015-05-07' '2015-05-28' '2015-04-13' '2015-03-25' '2015-07-21'
 '2015-06-27' '2015-07-18' '2015-07-23' '2015-06-08' '2015-06-22'
 '2015-06-24' '2015-03-05' '2015-06-01' '2015-04-24' '2015-07-22'
 '2015-05-27' '2015-04-06' '2015-04-11' '2015-07-25' '2015-07-28'
 '2015-07-29' '2015-06-25' '2015-07-24' '2015-06-05' '2015-06-30'
 '2015-06-13' '2015-06-11' '2015-07-30' '2015-07-27' '2015-04-29'
 '2015-06-04' '2015-07-26' '2015-08-01' '2015-08-02' '2015-06-15'
 '2015-04-23' '2015-07-31' '2015-05-25' '2015-08-03' '2015-04-17'
 '2015-08-04' '2015-08-06' '2015-05-15' '2015-05-09' '2015-03-17'
 '2015-05-22' '2015-08-07' '2015-04-04' '2015-08-05' '2015-08-08'
 '2015-08-10' '2015-05-04' '2015-06-06' '2015-08-09' '2015-08-15'
 '2015-08-11' '2015-03-28' '2015-08-14' '2015-08-12' '2015-08-16'
 '2015-05-16' '2015-08-21' '2015-08-13' '2015-08-17' '2015-04-20'
 '2015-08-18' '2015-08-23' '2015-08-22' '2015-08-19' '2015-08-20'
 '2015-08-29' '2015-03-31' '2015-05-30' '2015-08-25' '2015-04-14'
 '2015-08-24' '2015-03-24' '2015-05-21' '2015-08-28' '2015-08-26'
 '2015-08-27' '2015-08-30' '2015-08-31' '2015-09-06' '2015-09-03'
 '2015-09-04' '2015-09-02' '2015-09-01' '2015-09-05' '2015-06-20'
 '2015-09-07' '2015-09-10' '2015-09-11' '2015-09-08' '2015-09-09'
 '2015-09-13' '2015-09-15' '2015-04-10' '2015-01-02' '2014-11-18'
 '2015-09-12' '2015-09-17' '2015-09-14' '2015-04-07' '2015-09-19'
 '2015-09-16' '2015-09-20' '2015-01-18' '2015-10-23' '2015-01-22'
 '2015-01-01' '2015-09-22' '2015-09-24' '2015-09-18' '2015-09-21'
 '2015-09-30' '2015-09-25' '2015-09-27' '2015-09-28' '2015-10-12'
 '2015-09-29' '2015-09-23' '2015-10-01' '2015-09-26' '2015-04-18'
 '2015-10-02' '2015-10-04' '2015-10-08' '2015-10-03' '2015-10-07'
 '2015-10-09' '2015-10-11' '2015-10-05' '2015-10-06' '2015-10-10'
 '2015-10-14' '2015-10-15' '2015-10-18' '2015-10-13' '2015-10-20'
 '2015-10-19' '2015-10-31' '2015-10-16' '2015-10-21' '2015-10-22'
 '2015-10-17' '2015-10-24' '2015-10-25' '2015-10-28' '2015-10-27'
 '2015-10-26' '2015-10-30' '2015-11-05' '2015-10-29' '2015-11-03'
 '2015-11-07' '2015-11-04' '2015-11-01' '2015-11-02' '2015-11-17'
 '2015-11-06' '2015-11-10' '2015-11-08' '2015-11-09' '2015-11-15'
 '2015-11-16' '2015-11-11' '2015-11-12' '2015-11-14' '2015-11-13'
 '2015-11-18' '2015-11-22' '2015-11-19' '2015-11-21' '2015-11-20'
 '2015-11-24' '2015-11-25' '2015-11-23' '2015-11-28' '2015-11-26'
 '2015-11-27' '2015-11-29' '2015-12-04' '2015-12-01' '2015-12-06'
 '2015-12-08' '2015-12-02' '2015-12-03' '2015-12-31' '2015-12-05'
 '2015-12-10' '2015-12-17' '2015-11-30' '2015-12-12' '2015-12-07'
 '2016-01-05' '2015-12-11' '2015-12-13' '2015-12-15' '2015-12-16'
 '2015-12-19' '2015-12-18' '2015-12-26' '2015-12-27' '2015-12-22'
 '2015-12-23' '2015-12-24' '2015-12-29' '2015-12-28' '2015-12-20'
 '2015-12-30' '2016-01-02' '2016-01-01' '2015-12-25' '2016-01-03'
 '2016-01-04' '2016-01-11' '2016-01-07' '2015-12-21' '2016-01-09'
 '2016-01-10' '2016-01-08' '2016-01-06' '2016-01-12' '2016-01-13'
 '2016-01-23' '2016-02-09' '2016-01-15' '2016-01-16' '2016-01-17'
 '2016-01-19' '2016-01-18' '2016-01-21' '2016-01-24' '2016-01-22'
 '2016-01-29' '2016-01-27' '2016-01-25' '2016-03-08' '2016-01-26'
 '2016-01-20' '2016-01-30' '2016-02-01' '2016-02-02' '2016-02-08'
 '2016-02-07' '2016-01-28' '2016-02-05' '2016-02-03' '2016-02-13'
 '2016-02-10' '2016-02-04' '2016-02-12' '2016-02-11' '2016-02-16'
 '2016-02-14' '2016-02-15' '2016-02-20' '2016-02-06' '2016-01-14'
 '2016-02-17' '2016-02-21' '2016-02-24' '2016-02-25' '2016-02-19'
 '2016-02-18' '2016-02-26' '2016-02-23' '2016-03-05' '2016-02-22'
 '2016-02-27' '2016-03-03' '2016-03-24' '2016-03-04' '2016-02-29'
 '2016-03-01' '2016-03-02' '2016-03-30' '2016-03-07' '2016-03-14'
 '2016-03-21' '2016-03-09' '2016-03-12' '2016-03-22' '2016-03-10'
 '2016-03-11' '2016-03-20' '2016-03-15' '2016-03-17' '2016-03-16'
 '2016-03-19' '2016-03-27' '2016-03-18' '2016-03-26' '2016-03-31'
 '2016-03-28' '2016-03-29' '2016-04-01' '2016-03-23' '2016-04-02'
 '2016-03-25' '2016-03-13' '2016-04-04' '2016-04-03' '2016-04-05'
 '2016-04-08' '2016-04-06' '2016-04-09' '2016-04-12' '2016-04-16'
 '2016-04-17' '2016-04-27' '2016-04-14' '2016-04-18' '2016-04-21'
 '2016-04-19' '2016-04-20' '2016-04-10' '2016-04-13' '2016-04-11'
 '2016-04-07' '2016-04-15' '2016-04-22' '2016-04-23' '2016-04-26'
 '2016-04-28' '2016-04-24' '2016-04-25' '2016-04-29' '2016-04-30'
 '2016-05-01' '2016-05-10' '2016-05-02' '2016-05-07' '2016-05-08'
 '2016-05-12' '2016-05-04' '2016-05-06' '2016-05-03' '2016-05-09'
 '2016-05-05' '2016-05-13' '2016-05-14' '2016-05-18' '2016-05-19'
 '2016-05-15' '2016-05-16' '2016-05-11' '2016-05-21' '2016-05-22'
 '2016-05-20' '2016-05-24' '2016-05-25' '2016-05-26' '2016-05-23'
 '2016-05-27' '2016-05-17' '2016-05-29' '2016-05-28' '2016-05-30'
 '2016-05-31' '2016-06-01' '2016-06-03' '2016-06-08' '2016-06-02'
 '2016-06-05' '2016-06-06' '2016-06-13' '2016-06-07' '2016-06-10'
 '2016-06-11' '2016-06-16' '2016-06-12' '2016-06-14' '2016-06-17'
 '2016-06-04' '2016-06-18' '2016-06-21' '2016-06-09' '2016-06-24'
 '2016-06-20' '2016-06-25' '2016-06-22' '2016-06-26' '2016-06-23'
 '2016-07-01' '2016-06-15' '2016-06-28' '2016-07-02' '2016-06-19'
 '2016-06-27' '2016-07-04' '2016-06-30' '2016-07-05' '2016-07-08'
 '2016-07-09' '2016-07-07' '2016-07-12' '2016-06-29' '2016-07-10'
 '2016-07-15' '2016-07-03' '2016-07-16' '2016-07-14' '2016-07-18'
 '2016-07-13' '2016-07-06' '2016-07-20' '2016-07-21' '2016-07-23'
 '2016-07-19' '2016-07-11' '2016-07-28' '2016-07-17' '2016-07-25'
 '2016-07-22' '2016-07-29' '2016-08-03' '2016-08-02' '2016-08-04'
 '2016-08-08' '2016-08-10' '2016-08-01' '2016-08-06' '2016-03-06'
 '2016-08-05' '2016-07-26' '2016-08-07' '2016-07-30' '2016-07-24'
 '2016-08-12' '2016-07-27' '2016-08-13' '2016-08-18' '2016-08-16'
 '2016-08-15' '2016-08-17' '2016-08-11' '2016-07-31' '2016-08-19'
 '2016-09-01' '2016-08-23' '2016-08-26' '2016-08-20' '2016-08-21'
 '2016-09-04' '2016-08-22' '2016-08-27' '2016-08-25' '2016-08-09'
 '2016-09-05' '2016-08-24' '2016-09-10' '2016-08-29' '2016-09-09'
 '2016-08-30' '2016-09-13' '2016-08-31' '2016-09-14' '2016-09-12'
 '2016-09-15' '2016-08-14' '2016-09-02' '2016-09-08' '2016-09-19'
 '2016-09-16' '2016-09-07' '2016-09-21' '2016-09-06' '2016-09-22'
 '2016-09-17' '2016-09-20' '2016-09-03' '2016-09-26' '2016-09-23'
 '2016-09-18' '2016-09-29' '2016-10-02' '2016-10-01' '2016-09-27'
 '2016-09-25' '2016-10-05' '2016-09-11' '2016-09-30' '2016-10-09'
 '2016-10-03' '2016-10-06' '2016-10-11' '2016-09-24' '2016-10-13'
 '2016-09-28' '2016-10-08' '2016-10-07' '2016-10-16' '2016-08-28'
 '2016-10-17' '2016-10-18' '2016-10-10' '2016-10-04' '2016-10-15'
 '2016-10-19' '2016-10-21' '2016-10-12' '2016-10-24' '2016-10-26'
 '2016-10-23' '2016-10-20' '2016-10-25' '2016-10-27' '2016-10-28'
 '2016-10-30' '2016-10-29' '2016-11-01' '2016-11-04' '2016-10-14'
 '2016-11-07' '2016-11-03' '2016-11-10' '2016-11-14' '2016-11-02'
 '2016-10-31' '2016-11-11' '2016-11-08' '2016-11-05' '2016-11-25'
 '2016-11-09' '2016-11-20' '2016-11-21' '2016-10-22' '2016-11-22'
 '2016-11-16' '2016-11-23' '2016-11-17' '2016-11-06' '2016-11-15'
 '2016-11-13' '2016-11-12' '2016-11-27' '2016-11-19' '2016-11-30'
 '2016-11-18' '2016-12-02' '2016-12-04' '2016-11-29' '2016-12-07'
 '2016-11-28' '2016-12-03' '2016-12-06' '2016-11-24' '2016-12-08'
 '2016-12-05' '2016-12-10' '2016-12-13' '2016-12-14' '2016-12-16'
 '2016-12-15' '2016-12-17' '2016-12-19' '2016-12-21' '2016-12-20'
 '2016-12-22' '2016-12-23' '2016-12-24' '2016-12-01' '2016-12-27'
 '2016-12-29' '2016-12-30' '2016-12-12' '2017-01-02' '2016-12-11'
 '2017-01-03' '2017-01-04' '2017-01-01' '2016-12-26' '2017-01-06'
 '2016-12-28' '2016-12-18' '2017-01-10' '2017-01-11' '2017-01-07'
 '2017-01-12' '2017-01-16' '2017-01-14' '2017-01-13' '2017-01-05'
 '2017-01-17' '2017-01-20' '2016-12-09' '2017-01-26' '2016-12-31'
 '2017-01-23' '2017-01-27' '2017-01-28' '2017-01-19' '2017-01-25'
 '2017-01-24' '2017-01-29' '2017-01-18' '2016-12-25' '2017-01-15'
 '2017-01-21' '2017-02-01' '2017-02-02' '2017-01-31' '2017-02-03'
 '2017-02-04' '2017-02-06' '2017-02-07' '2017-02-08' '2017-01-30'
 '2017-02-09' '2017-01-09' '2017-02-11' '2017-02-10' '2017-02-12'
 '2017-02-13' '2017-02-14' '2017-02-16' '2017-02-17' '2017-02-18'
 '2017-02-19' '2017-02-20' '2017-02-15' '2017-02-21' '2017-02-22'
 '2017-02-26' '2017-02-23' '2017-02-24' '2017-02-25' '2017-02-28'
 '2017-03-05' '2017-02-27' '2017-03-03' '2017-03-06' '2017-03-02'
 '2017-03-08' '2017-03-09' '2017-03-10' '2017-03-07' '2017-03-12'
 '2017-03-13' '2017-03-14' '2017-03-01' '2017-03-18' '2017-03-17'
 '2017-03-24' '2017-03-22' '2017-03-26' '2017-03-27' '2017-03-11'
 '2017-03-28' '2017-03-29' '2017-03-30' '2017-03-31' '2017-03-19'
 '2017-01-22' '2017-04-02' '2017-03-20' '2017-04-03' '2017-01-08'
 '2017-03-23' '2017-04-05' '2017-02-05' '2017-04-04' '2017-03-15'
 '2017-04-07' '2017-03-25' '2017-04-08' '2017-04-06' '2017-03-21'
 '2017-04-10' '2017-04-01' '2017-04-11' '2017-04-13' '2017-04-15'
 '2017-04-12' '2017-03-04' '2017-04-19' '2017-04-22' '2017-04-20'
 '2017-05-02' '2017-04-09' '2017-04-23' '2017-04-24' '2017-04-16'
 '2017-04-28' '2017-04-18' '2017-04-26' '2017-04-25' '2017-04-17'
 '2017-04-21' '2017-05-03' '2017-05-04' '2017-03-16' '2017-05-05'
 '2017-04-29' '2017-04-14' '2017-05-08' '2017-04-27' '2017-05-11'
 '2017-05-01' '2017-05-10' '2017-05-13' '2017-05-06' '2017-05-14'
 '2017-05-16' '2017-04-30' '2017-05-15' '2017-05-07' '2017-05-09'
 '2017-05-17' '2017-05-21' '2017-05-12' '2017-05-22' '2017-05-24'
 '2017-05-23' '2017-05-25' '2017-05-26' '2017-05-28' '2017-05-27'
 '2017-05-29' '2017-05-19' '2017-05-31' '2017-05-20' '2017-06-01'
 '2017-05-30' '2017-06-02' '2016-11-26' '2017-06-04' '2017-06-05'
 '2017-06-06' '2017-06-07' '2017-05-18' '2017-06-09' '2017-06-10'
 '2017-06-11' '2017-06-12' '2017-06-14' '2017-06-08' '2017-06-16'
 '2017-06-13' '2017-06-03' '2017-06-24' '2017-06-20' '2017-06-19'
 '2017-06-21' '2017-06-26' '2017-06-27' '2017-06-22' '2017-06-28'
 '2017-06-15' '2017-06-29' '2017-06-30' '2017-06-18' '2017-07-04'
 '2017-07-08' '2017-07-05' '2017-07-03' '2017-07-07' '2017-07-01'
 '2017-07-06' '2017-07-11' '2017-07-12' '2017-06-23' '2017-07-13'
 '2017-07-02' '2017-07-10' '2017-07-14' '2017-07-15' '2017-07-16'
 '2017-07-18' '2017-07-17' '2017-07-19' '2017-07-20' '2017-07-21'
 '2017-06-25' '2017-06-17' '2017-07-24' '2017-07-26' '2017-07-09'

##*2. Quality Audit*

In [7]:
#after Duplicate data remove
df.shape

(87396, 32)

In [8]:
#missing values
df.isna().sum().sort_values(ascending=False)

company                           82137
agent                             12193
country                             452
children                              4
arrival_date_month                    0
arrival_date_week_number              0
hotel                                 0
is_canceled                           0
stays_in_weekend_nights               0
arrival_date_day_of_month             0
adults                                0
stays_in_week_nights                  0
babies                                0
meal                                  0
lead_time                             0
arrival_date_year                     0
distribution_channel                  0
market_segment                        0
previous_bookings_not_canceled        0
is_repeated_guest                     0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
previous_cancellations                0
deposit_type                          0
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

In [9]:
#containng abnorma values
df["meal"].unique()

array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object)

In [10]:
df["market_segment"].unique()

array(['Direct', 'Corporate', 'Online TA', 'Offline TA/TO',
       'Complementary', 'Groups', 'Undefined', 'Aviation'], dtype=object)

In [11]:
df["distribution_channel"].unique()

array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object)

##*3. Suspicious Values*

In [12]:
#1. negetive adr
(df['adr'] < 0).sum()

np.int64(1)

In [13]:
#2. company column has huge missing value which is not good for model
df["company"].isna().sum()

np.int64(82137)

In [14]:
#3. presence of outliers ,as mean =106.337246 and max	= 5400.000000
df["adr"].describe()

count    87396.000000
mean       106.337246
std         55.013953
min         -6.380000
25%         72.000000
50%         98.100000
75%        134.000000
max       5400.000000
Name: adr, dtype: float64

#R3

In [15]:
group_stats = df.groupby('is_repeated_guest')['is_canceled'].agg(['mean','count'])
print(group_stats)

                       mean  count
is_repeated_guest
0                  0.282969  83981
1                  0.076428   3415

In [16]:
p1 = df[df['is_repeated_guest']==0]['is_canceled'].mean()
n1 = len(df[df['is_repeated_guest']==0])

p2 = df[df['is_repeated_guest']==1]['is_canceled'].mean()
n2 = len(df[df['is_repeated_guest']==1])

diff = p2 - p1

se = np.sqrt((p1*(1-p1))/n1 + (p2*(1-p2))/n2)

lower = diff - 1.96*se
upper = diff + 1.96*se

print("Difference =", diff)
print("95% CI =", (lower, upper))

Difference = -0.2065412411226042
95% CI = (np.float64(-0.21595852552257713), np.float64(-0.19712395672263125))

#R4

In [17]:
df['lead_band'] = pd.cut(
    df['lead_time'],
    bins=[0,30,90,180,737],
    labels=['0-30','31-90','91-180','180+']
)

In [18]:
pd.crosstab(df['lead_band'], df['is_repeated_guest'])

is_repeated_guest      0     1
lead_band
0-30               26717  1949
31-90              22560   184
91-180             18138   105
180+               11677    88

In [19]:
df.groupby(
    ['lead_band','is_repeated_guest']
)['is_canceled'].mean()

/tmp/ipykernel_700/4174408592.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(

lead_band  is_repeated_guest
0-30       0                    0.194408
           1                    0.072345
31-90      0                    0.321676
           1                    0.125000
91-180     0                    0.351252
           1                    0.104762
180+       0                    0.397534
           1                    0.375000
Name: is_canceled, dtype: float64

#R5

In [20]:
# Sensitivity Analysis - Alternative 1

df['lead_band_v1'] = pd.cut(
    df['lead_time'],
    bins=[0,30,90,180,737],
    labels=['0-30','31-90','91-180','180+']
)

df.groupby(['lead_band_v1','is_repeated_guest'])['is_canceled'].mean()

/tmp/ipykernel_700/3149892239.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['lead_band_v1','is_repeated_guest'])['is_canceled'].mean()

lead_band_v1  is_repeated_guest
0-30          0                    0.194408
              1                    0.072345
31-90         0                    0.321676
              1                    0.125000
91-180        0                    0.351252
              1                    0.104762
180+          0                    0.397534
              1                    0.375000
Name: is_canceled, dtype: float64

In [21]:
# Sensitivity Analysis - Alternative 2

df['lead_band_v2'] = pd.cut(
    df['lead_time'],
    bins=[0,60,120,240,737],
    labels=['0-60','61-120','121-240','240+']
)

df.groupby(['lead_band_v2','is_repeated_guest'])['is_canceled'].mean()

/tmp/ipykernel_700/2389126448.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['lead_band_v2','is_repeated_guest'])['is_canceled'].mean()

lead_band_v2  is_repeated_guest
0-60          0                    0.235315
              1                    0.075882
61-120        0                    0.336928
              1                    0.109091
121-240       0                    0.356789
              1                    0.204082
240+          0                    0.437928
              1                    0.387755
Name: is_canceled, dtype: float64

In [22]:
# Sensitivity Analysis - Alternative 3

df.groupby(['hotel','is_repeated_guest'])['is_canceled'].mean()

hotel         is_repeated_guest
City Hotel    0                    0.306651
              1                    0.110656
Resort Hotel  0                    0.245002
              1                    0.042179
Name: is_canceled, dtype: float64

In [23]:
# Sensitivity Analysis - Alternative 4

q1 = df["lead_time"].quantile(0.25)
q3 = df["lead_time"].quantile(0.75)

iqr = q3 - q1

lower = q1 - 1.5*iqr
upper = q3 + 1.5*iqr

df_no_outliers = df[
    (df["lead_time"] >= lower) &
    (df["lead_time"] <= upper)
]

df_no_outliers.groupby('is_repeated_guest')['is_canceled'].mean()

is_repeated_guest
0    0.277798
1    0.074249
Name: is_canceled, dtype: float64